"use client";

import { useState, useTransition } from "react";

import {
  createWhatsAppUploadLinkAction,
  generateFollowUpDraftAction,
  sendFollowUpWhatsAppAction
} from "@/lib/actions/whatsapp-messages";
import { sendFollowUpEmailAction } from "@/lib/actions/email-messages";
import type { EmailMessageType } from "@/lib/email/templates";
import type { MessageType } from "@/lib/types";

import { SendWhatsAppButton } from "./send-whatsapp-button";

const messageTypes: Array<{ value: MessageType; label: string }> = [
  { value: "upload_link", label: "Upload link" },
  { value: "missing_documents", label: "Missing documents" },
  { value: "reupload_required", label: "Reupload required" },
  { value: "verification_required", label: "Verification required" },
  { value: "file_complete", label: "File complete" }
];

export function FollowUpMessageGenerator({
  studentId,
  initialBody,
  initialUploadLink,
  hasActiveUploadToken,
  studentEmail,
  emailConfigured,
  whatsappConfigured
}: {
  studentId: string;
  initialBody: string;
  initialUploadLink?: string | null;
  hasActiveUploadToken?: boolean;
  studentEmail?: string | null;
  emailConfigured: boolean;
  whatsappConfigured: boolean;
}) {
  const [body, setBody] = useState(initialBody);
  const [messageType, setMessageType] = useState<MessageType>("upload_link");
  const [uploadLink, setUploadLink] = useState(initialUploadLink || "");
  const [status, setStatus] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const canSend = body.trim().length > 0;

  function generateUploadLink() {
    setStatus(null);
    startTransition(async () => {
      const result = await createWhatsAppUploadLinkAction({ studentId });

      if (!result.ok) {
        setStatus(`Upload link failed: ${result.error}`);
        return;
      }

      setUploadLink(result.uploadLink);
      setStatus(`Upload link ready. Expires ${result.expiresAt}.`);
    });
  }

  function generateDraft() {
    setStatus(null);
    startTransition(async () => {
      const draft = await generateFollowUpDraftAction({
        studentId,
        messageType,
        uploadLink
      });
      setBody(draft.body);
      setStatus(`Draft generated by ${draft.source}.`);
    });
  }

  function sendMessage() {
    setStatus(null);
    startTransition(async () => {
      const result = await sendFollowUpWhatsAppAction({
        studentId,
        messageType,
        body
      });
      setStatus(
        result.ok
          ? `Sent via Twilio: ${result.status}`
          : `Failed: ${result.error || "Twilio send failed."}`
      );
    });
  }

  function sendEmailMessage() {
    setStatus(null);
    startTransition(async () => {
      const emailType: EmailMessageType =
        messageType === "upload_link"
          ? "student_upload_link"
          : messageType === "reupload_required"
            ? "reupload_required"
            : messageType === "file_complete"
              ? "file_complete"
              : "missing_document_reminder";
      const result = await sendFollowUpEmailAction({
        studentId,
        messageType: emailType,
        uploadLink
      });
      setStatus(
        result.ok
          ? "Email sent through Resend."
          : `Email failed: ${result.error || "Email provider failed."}`
      );
    });
  }

  return (
    <section className="panel section-stack">
      <div className="section-title">
        <div>
          <h2>WhatsApp follow-up</h2>
          <p>Generate a polite draft, edit it, then send through Twilio.</p>
        </div>
      </div>
      {hasActiveUploadToken && !uploadLink ? (
        <div className="alert info">
          An active upload token exists, but the raw link is only shown when it is generated.
          Generate a new link to send it on WhatsApp.
        </div>
      ) : null}
      <div className="form-grid two">
        <label>
          Message type
          <select
            value={messageType}
            onChange={(event) => setMessageType(event.currentTarget.value as MessageType)}
          >
            {messageTypes.map((type) => (
              <option key={type.value} value={type.value}>
                {type.label}
              </option>
            ))}
          </select>
        </label>
        <label>
          Upload link
          <input
            readOnly
            placeholder="Generate a secure upload link"
            value={uploadLink}
          />
        </label>
      </div>
      <div className="button-row">
        <button
          className="button secondary"
          disabled={isPending}
          type="button"
          onClick={generateUploadLink}
        >
          {uploadLink ? "Regenerate upload link" : "Generate upload link"}
        </button>
        <button
          className="button secondary"
          disabled={isPending}
          type="button"
          onClick={generateDraft}
        >
          {isPending ? "Working..." : "Generate message"}
        </button>
      </div>
      <label>
        Editable WhatsApp message
        <textarea
          className="message-box"
          value={body}
          onChange={(event) => setBody(event.target.value)}
          rows={9}
        />
      </label>
      {status ? <div className="alert info">{status}</div> : null}
      <div className="button-row">
        <SendWhatsAppButton
          disabled={!canSend || !whatsappConfigured}
          isPending={isPending}
          onSend={sendMessage}
        />
        <button
          className="button secondary"
          disabled={
            isPending ||
            !studentEmail ||
            !emailConfigured ||
            (messageType === "upload_link" && !uploadLink)
          }
          type="button"
          onClick={sendEmailMessage}
        >
          {isPending ? "Working..." : "Send Email"}
        </button>
      </div>
      {!whatsappConfigured ? (
        <p className="muted">Twilio WhatsApp is not configured.</p>
      ) : (
        <p className="muted">
          Sandbox/testing mode: messages are sent using Twilio Sandbox.
          Production agency-owned sender will be added later.
        </p>
      )}
      {!studentEmail ? (
        <p className="muted">Add a student email address to use email fallback.</p>
      ) : !emailConfigured ? (
        <p className="muted">Email provider not configured.</p>
      ) : null}
    </section>
  );
}
